# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trimr < Formula
  desc "Trim those unused branches with ease."
  homepage ""
  version "0.1.6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/FuzzyStatic/trimr/releases/download/v0.1.6/trimr_0.1.6_Darwin_x86_64.tar.gz"
    sha256 "f63c416e58ba30e1998aa62a51d2458c22127df9409d4a6481a40f0253b7c9fb"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/FuzzyStatic/trimr/releases/download/v0.1.6/trimr_0.1.6_Darwin_arm64.tar.gz"
    sha256 "bf24c78de2f65fcfa0170f155a69a01612569abe538a4d87cf35d8803aecad01"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/FuzzyStatic/trimr/releases/download/v0.1.6/trimr_0.1.6_Linux_x86_64.tar.gz"
    sha256 "ca73918baecb387fd4515c86800727383d9b4ab7f6bb257bc6be10caccb22859"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/FuzzyStatic/trimr/releases/download/v0.1.6/trimr_0.1.6_Linux_arm64.tar.gz"
    sha256 "9df9cdf0074aadb0424f1168ae51277162079998cb0de9cfddd75f2228b013fb"
  end

  def install
    bin.install "trimr"
  end
end
